### PR TITLE
Added Kotlin codestarter

### PR DESCRIPTION
**Pull request by janpk**
I tried to add test for the kotlin code starter to the integration-tests module, but the test failed with 

```
[ERROR] Failures:
[ERROR]   CodestartKotlinTest.testContent:21 [corresponding snapshot file not found for CodestartKotlinTest/testContent/src_main_kotlin_ilove_quark_us_MyAction.kt (Use -Dsnap to create it automatically)]
Expecting path:
  /Users/jan-petter/gitrepos/github/quarkus-github-action/integration-tests/target/test-classes/__snapshots__/CodestartKotlinTest/testContent/src_main_kotlin_ilove_quark_us_MyAction.kt
to exist (symbolic links were followed).
```

so did not include it in this PR

### CODE REVIEW

**Review by gsmet — APPROVED** [review]
Thanks, I pushed a test to your PR, let's see what CI has to say.

**Comment by gsmet** [comment]
In fact, just running the build with `-Dsnap` generates them for you the first time.

Then you need to check things actually make sense and the tests will ensure it will stay that way.

**Comment by gsmet** [comment]
I backported this change to `1.x` and will release new versions for both `2.x` and `1.x` tomorrow.

**Comment by gsmet** [comment]
@janpk `1.0.2` and `2.0.0.Alpha2` are available on Maven Central with your work included.

**Comment by janpk** [comment]
Great. Thank you!

**Pull request merged**
